apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: serverless-

resources:
- service.yaml
- configmap.yaml

labels:
- includeSelectors: true
  pairs:
    component: serverless

