apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: serverless-

resources:
- service.yaml
- configmap.yaml

labels:
- includeSelectors: true
  pairs:
    app: code-with-quarkus
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/part-of: quarkus-application

