apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: code-with-quarkus
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
      - name: serverless-troubleshooting
        image: serverless-troubleshooting:1.0.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: QUARKUS_HTTP_HOST
          valueFrom:
            configMapKeyRef:
              name: code-with-quarkus-config
              key: QUARKUS_HTTP_HOST
        - name: QUARKUS_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: code-with-quarkus-config
              key: QUARKUS_HTTP_PORT
        - name: QUARKUS_LOG_CONSOLE_ENABLE
          valueFrom:
            configMapKeyRef:
              name: code-with-quarkus-config
              key: QUARKUS_LOG_CONSOLE_ENABLE
        - name: QUARKUS_LOG_CONSOLE_FORMAT
          valueFrom:
            configMapKeyRef:
              name: code-with-quarkus-config
              key: QUARKUS_LOG_CONSOLE_FORMAT
        - name: QUARKUS_LOG_CONSOLE_LEVEL
          valueFrom:
            configMapKeyRef:
              name: code-with-quarkus-config
              key: QUARKUS_LOG_CONSOLE_LEVEL
        - name: QUARKUS_LOG_CATEGORY_ORG_ACME_LEVEL
          valueFrom:
            configMapKeyRef:
              name: code-with-quarkus-config
              key: QUARKUS_LOG_CATEGORY_ORG_ACME_LEVEL
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 64Mi
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30