apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- route.yaml

namePrefix: native-

commonLabels:
  variant: native

images:
- name: serverless-troubleshooting
  newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
  newTag: d140ec3-native

patches:
- path: deployment-patch.yaml
