apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: native-

labels:
- includeSelectors: true
  pairs:
    variant: native
    app: quarkus-native-deployment
    app.kubernetes.io/name: quarkus-native-deployment
    app.kubernetes.io/part-of: quarkus-native-application

images:
- name: serverless-troubleshooting
  newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
  newTag: 4ad6e19-native

patches:
- path: deployment-patch.yaml
- path: route-patch.yaml
