apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jdk-deployment
  namespace: openshift-gitops
  labels:
    app: code-with-quarkus
    variant: jdk
    type: deployment
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-telco-adoption/serverless-troubleshooting.git
    targetRevision: main
    path: kubernetes/deployment/overlays/jdk
  destination:
    server: https://kubernetes.default.svc
    namespace: serverless-troubleshooting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true