apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: native-deployment
  namespace: argocd
  labels:
    app: code-with-quarkus
    variant: native
    type: deployment
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-telco-adoption/code-with-quarkus.git
    targetRevision: main
    path: kubernetes/deployment/overlays/native
  destination:
    server: https://kubernetes.default.svc
    namespace: code-with-quarkus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true