apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: jdk-

patches:
- path: deployment-patch.yaml
- path: route-patch.yaml

images:
- name: serverless-troubleshooting
  newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
  newTag: d140ec3-jdk

labels:
- includeSelectors: true
  pairs:
    variant: jdk
    app: quarkus-jdk-deployment
    app.kubernetes.io/name: quarkus-jdk-deployment
    app.kubernetes.io/part-of: quarkus-jdk-application
