apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: deployment-

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- route.yaml

labels:
- includeSelectors: true
  pairs:
    component: deployment
