apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: jdk-

patches:
- path: service-patch.yaml
images:
- name: serverless-troubleshooting
  newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
  newTag: 4ad6e19-jdk
labels:
- includeSelectors: true
  pairs:
    variant: jdk
    app: quarkus-jdk-serverless
    app.kubernetes.io/name: quarkus-jdk-serverless
    app.kubernetes.io/part-of: quarkus-jdk-application
