apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: code-with-quarkus
spec:
  template:
    spec:
      containers:
      - name: code-with-quarkus
        image: serverless-troubleshooting
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
            cpu: 100m