apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: native-


patches:
- path: service-patch.yaml
images:
- name: serverless-troubleshooting
  newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
  newTag: 4ad6e19-native
labels:
- includeSelectors: true
  pairs:
    variant: native
    app: quarkus-native-serverless
    app.kubernetes.io/name: quarkus-native-serverless
    app.kubernetes.io/part-of: quarkus-native-application
