apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: native-


patches:
- path: service-patch.yaml
images:
- name: serverless-troubleshooting
  newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
  newTag: d140ec3-native
labels:
- includeSelectors: true
  pairs:
    variant: native
