apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: code-with-quarkus
spec:
  template:
    spec:
      containers:
      - name: code-with-quarkus
        image: quay.io/redhat-telco-adoption/serverless-troubleshooting:1.0.1-native
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
            cpu: 50m