apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - route.yaml

namePrefix: native-

commonLabels:
  variant: native

images:
  - name: code-with-quarkus
    newName: quay.io/redhat-telco-adoption/serverless-troubleshooting
    newTag: 1.0.1-native

patchesStrategicMerge:
  - deployment-patch.yaml